from __future__ import annotations

from sqlalchemy import select

from app.domain.enums import ContentItemType
from app.domain.models import ContentItem
from app.infra.db.session import SessionLocal


BASE_SEED_ITEMS = [
    {"type": ContentItemType.COURSE, "title": "Python para Automacao Profissional", "description": "Curso pratico de automacao com Python para ganhar produtividade no trabalho.", "external_url": "https://www.freecodecamp.org/news/tag/python/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["python", "automation", "growth", "performance"]},
    {"type": ContentItemType.ARTICLE, "title": "Como Criar um Plano de Carreira Tecnica", "description": "Guia para definir metas trimestrais e mapear lacunas de habilidades.", "external_url": "https://roadmap.sh/guides", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["career", "growth", "planning"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Mapear Competencias da Vaga Atual", "description": "Liste as 10 competencias mais exigidas no seu cargo e autoavalie seu nivel.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["growth", "self-assessment", "performance"]},
    {"type": ContentItemType.CERTIFICATION, "title": "AWS Cloud Practitioner", "description": "Certificacao base para validar conhecimento de fundamentos cloud.", "external_url": "https://aws.amazon.com/certification/certified-cloud-practitioner/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["cloud", "certification", "growth", "switch"]},
    {"type": ContentItemType.COURSE, "title": "SQL para Analise de Dados", "description": "Curso de SQL com foco em consultas para tomada de decisao.", "external_url": "https://www.khanacademy.org/computing/computer-programming/sql", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["sql", "analytics", "growth"]},
    {"type": ContentItemType.COURSE, "title": "Fundamentos de Product Analytics", "description": "Aprenda metricas de produto e experimentacao orientada a dados.", "external_url": "https://www.coursera.org/articles/product-analytics", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["analytics", "product", "switch", "portfolio"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Projeto de Portfolio: Dashboard de Negocio", "description": "Construa um dashboard completo e publique no GitHub para portfolio.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["portfolio", "switch", "project"]},
    {"type": ContentItemType.ARTICLE, "title": "Como Fazer Networking para Transicao de Carreira", "description": "Estrategias de networking para encontrar oportunidades na nova area.", "external_url": "https://www.linkedin.com/pulse/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["switch", "networking", "career"]},
    {"type": ContentItemType.COURSE, "title": "Git e GitHub para Mudanca de Carreira", "description": "Controle de versao, colaboracao e boas praticas para portfolio tecnico.", "external_url": "https://docs.github.com/en/get-started/start-your-journey/about-github-and-git", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["switch", "portfolio", "github"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Simulacao de Entrevista Tecnica", "description": "Execute 3 simulacoes de entrevista com feedback estruturado.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["interview", "switch", "practice"]},
    {"type": ContentItemType.COURSE, "title": "Ingles para Entrevistas Tecnicas", "description": "Vocabulos e estruturas para entrevistas em ingles no mercado global.", "external_url": "https://www.bbc.co.uk/learningenglish", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["english", "international", "interview", "abroad"]},
    {"type": ContentItemType.ARTICLE, "title": "Preparacao de CV Internacional", "description": "Como adaptar curriculo e perfil para candidaturas globais.", "external_url": "https://www.indeed.com/career-advice/resumes-cover-letters", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["international", "remote", "abroad"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Aplicar para 10 Vagas Remotas Internacionais", "description": "Plano semanal de aplicacoes com rastreamento de respostas.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["remote", "international", "abroad"]},
    {"type": ContentItemType.CERTIFICATION, "title": "IELTS Preparation Track", "description": "Preparacao estruturada para certificacao de proficiencia em ingles.", "external_url": "https://www.ielts.org/for-test-takers/sample-test-questions", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["english", "abroad", "certification"]},
    {"type": ContentItemType.ARTICLE, "title": "Guia de Vistos para Profissionais de Tecnologia", "description": "Visao geral de tipos de visto e requisitos mais comuns.", "external_url": "https://www.gov.uk/browse/visas-immigration/work-visas", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["visa", "international", "move-abroad"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Checklist de Documentacao para Relocacao", "description": "Organize documentos essenciais para processos de mudanca internacional.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["relocation", "visa", "planning", "move-abroad"]},
    {"type": ContentItemType.COURSE, "title": "Cultura de Trabalho Global", "description": "Boas praticas de comunicacao e colaboracao em times multiculturais.", "external_url": "https://www.coursera.org/learn/intercultural-communication", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["culture", "international", "move-abroad"]},
    {"type": ContentItemType.ARTICLE, "title": "Planejamento Financeiro para Mudanca de Pais", "description": "Como montar reserva, custo de vida e estrategia de transicao.", "external_url": "https://www.investopedia.com/personal-finance-4427765", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["relocation", "planning", "move-abroad"]},
    {"type": ContentItemType.COURSE, "title": "Negociacao Salarial Internacional", "description": "Tecnicas para negociar proposta em moeda estrangeira.", "external_url": "https://www.coursera.org/articles/salary-negotiation", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["international", "career", "move-abroad"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Plano de 90 Dias para Nova Funcao", "description": "Defina objetivos de impacto para os primeiros 90 dias na nova vaga.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["growth", "career", "execution"]},
    {"type": ContentItemType.COURSE, "title": "Storytelling para Entrevistas", "description": "Estruture respostas com metodo STAR para aumentar aprovacoes.", "external_url": "https://www.themuse.com/advice/star-interview-method", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["interview", "switch", "abroad"]},
    {"type": ContentItemType.ARTICLE, "title": "Guia de Portfolio para Profissionais de Dados", "description": "Exemplos de projetos e narrativa para portfolio de dados.", "external_url": "https://www.kaggle.com/learn", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["portfolio", "switch", "growth"]},
    {"type": ContentItemType.CERTIFICATION, "title": "Azure Fundamentals AZ-900", "description": "Certificacao introdutoria para validar base em cloud Azure.", "external_url": "https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["cloud", "certification", "switch", "growth"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Plano Semanal de Estudos 6h", "description": "Template para planejamento semanal de estudos com revisao.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["planning", "growth", "discipline"]},
    {"type": ContentItemType.ARTICLE, "title": "Como Medir Evolucao de Competencias", "description": "Defina indicadores de progresso e checkpoints mensais.", "external_url": "https://www.atlassian.com/team-playbook/examples/retrospective", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["growth", "metrics", "career"]},
    {"type": ContentItemType.COURSE, "title": "Comunicacao Assincrona para Times Remotos", "description": "Praticas para colaborar bem em empresas globais remotas.", "external_url": "https://about.gitlab.com/company/culture/all-remote/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["remote", "international", "abroad"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Revisao de LinkedIn para Mercado Global", "description": "Atualize headline, about e experiencias com foco internacional.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["international", "networking", "abroad"]},
    {"type": ContentItemType.CERTIFICATION, "title": "Scrum Fundamentals", "description": "Certificacao base para trabalho em times ageis.", "external_url": "https://www.scrumstudy.com/certification/scrum-fundamentals-certified", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["growth", "teamwork", "career"]},
    {"type": ContentItemType.ARTICLE, "title": "Roteiro para Migracao de Area em 6 Meses", "description": "Plano pratico para transicao de carreira em ciclos quinzenais.", "external_url": "https://roadmap.sh/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["switch", "planning", "career"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Revisao Quinzenal de Progresso", "description": "Cerimonia pessoal para avaliar entregas e ajustar metas.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["growth", "planning", "execution"]},
    {"type": ContentItemType.VIDEO, "title": "Como montar um plano de estudos realista", "description": "Video curto com estrategia para definir rotina e evitar sobrecarga.", "external_url": None, "video_url": "https://www.youtube.com/embed/TQMbvJNRpLE", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["growth", "planning", "discipline"]},
    {"type": ContentItemType.VIDEO, "title": "Portfolio tech que chama entrevistas", "description": "Explicacao pratica de como transformar projetos em portfolio convincente.", "external_url": None, "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["portfolio", "switch", "career"]},
    {"type": ContentItemType.VIDEO, "title": "Ingles para entrevistas globais", "description": "Aula focada em respostas para entrevistas internacionais.", "external_url": None, "video_url": "https://www.youtube.com/embed/9bZkp7q19f0", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["english", "interview", "abroad"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: maturidade de carreira atual", "description": "Teste rapido para mapear seu nivel de preparo para crescer na funcao atual.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce tem metas trimestrais definidas?", "options": ["Sim", "Nao", "Parcialmente"], "correctIndex": 0}, {"prompt": "Com que frequencia voce revisa suas competencias?", "options": ["Mensalmente", "Raramente", "Nunca"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["growth", "self-assessment", "quiz"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: prontidao para transicao de carreira", "description": "Descubra se seu portfolio e narrativa estao prontos para uma mudanca de area.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Seu portfolio mostra projetos com contexto e resultado?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce consegue explicar sua mudanca de carreira em 30 segundos?", "options": ["Sim", "Ainda nao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["switch", "portfolio", "quiz"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: prontidao internacional", "description": "Teste rapido sobre CV, ingles e documentacao para vagas globais.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Seu curriculo esta em ingles?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce conhece o processo de visto do destino?", "options": ["Sim", "Nao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["abroad", "international", "quiz"]},
    {"type": ContentItemType.DIAGRAM, "title": "Mapa visual de crescimento na carreira atual", "description": "Diagrama com as fases principais para ganhar escopo, influencia e senioridade.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": "https://placehold.co/1200x800/13111c/c4b5fd?text=Growth+Roadmap", "form_schema": None, "tags": ["growth", "diagram", "roadmap"]},
    {"type": ContentItemType.DIAGRAM, "title": "Mapa visual de transicao de carreira", "description": "Roadmap visual para portfolio, networking e entrevistas na nova area.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": "https://placehold.co/1200x800/111827/c4b5fd?text=Switch+Roadmap", "form_schema": None, "tags": ["switch", "diagram", "roadmap"]},
    {"type": ContentItemType.DIAGRAM, "title": "Mapa visual para carreira internacional", "description": "Fluxo visual entre ingles, CV, networking e aplicacoes globais.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": "https://placehold.co/1200x800/0f172a/c4b5fd?text=Global+Career+Roadmap", "form_schema": None, "tags": ["abroad", "diagram", "international"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Construa seu pitch de 30 segundos", "description": "Preencha um roteiro guiado para transformar sua experiencia em um pitch claro.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "targetRole", "label": "Cargo-alvo", "type": "text", "placeholder": "Ex: Cloud Engineer"}, {"name": "evidence", "label": "Prova principal", "type": "textarea", "placeholder": "Resultado concreto que mostra seu valor"}, {"name": "difference", "label": "Seu diferencial", "type": "textarea", "placeholder": "O que te destaca dos demais candidatos"}]}, "tags": ["switch", "form", "interview", "career"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Resumo profissional para LinkedIn global", "description": "Monte um resumo profissional em ingles com foco internacional.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "headline", "label": "Headline", "type": "text", "placeholder": "Ex: Data Analyst focused on product metrics"}, {"name": "summary", "label": "Resumo", "type": "textarea", "placeholder": "Quem voce e, impacto gerado e objetivo internacional"}]}, "tags": ["abroad", "form", "linkedin", "international"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Plano de crescimento de 90 dias", "description": "Estruture objetivos, metricas e stakeholders para sua evolucao na funcao atual.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "goal90", "label": "Meta principal em 90 dias", "type": "text", "placeholder": "Ex: liderar uma melhoria de processo"}, {"name": "metrics", "label": "Metricas de sucesso", "type": "textarea", "placeholder": "Como voce vai medir o resultado"}, {"name": "support", "label": "Quem precisa te apoiar", "type": "textarea", "placeholder": "Gestor, colegas, outras areas"}]}, "tags": ["growth", "form", "planning", "execution"]},
]

SOFT_SKILL_SEED_ITEMS = [
    {"type": ContentItemType.ARTICLE, "title": "Comunicacao clara em times tech", "description": "Como comunicar riscos, progresso e decisoes tecnicas sem ruido.", "external_url": "https://about.gitlab.com/company/culture/all-remote/communication/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:tech", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Feedback para engenheiros", "description": "Video sobre como dar e receber feedback com objetividade em produto e engenharia.", "external_url": None, "video_url": "https://www.youtube.com/embed/7wUCyjiyXdg", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:tech", "feedback"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: colaboracao em tecnologia", "description": "Verifique sua prontidao para colaborar melhor com produto, design e engenharia.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce registra decisoes tecnicas importantes?", "options": ["Sempre", "As vezes", "Nunca"], "correctIndex": 0}, {"prompt": "Voce alinha expectativas antes de iniciar um trabalho?", "options": ["Sim", "Nao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:tech", "teamwork"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Retro pessoal de sprint", "description": "Faça uma retro curta sobre comunicacao, foco e bloqueios da sua semana.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:tech", "reflection"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Plano de alinhamento tecnico", "description": "Estruture como voce vai comunicar status, riscos e proximos passos em projetos tech.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "stakeholders", "label": "Stakeholders principais", "type": "text", "placeholder": "Ex: PM, Tech Lead"}, {"name": "risks", "label": "Riscos que precisa comunicar", "type": "textarea", "placeholder": "Liste os principais riscos do ciclo atual"}]}, "tags": ["soft-skill", "career-type:tech", "communication"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Ordene uma conversa de feedback tecnico", "description": "Organize os passos de uma conversa de feedback dificil com um dev junior.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "order", "prompt": "Arraste para a ordem ideal.", "pieces": [{"id": "prepare", "label": "Preparar contexto e exemplos"}, {"id": "ask", "label": "Ouvir a percepcao da pessoa"}, {"id": "share", "label": "Compartilhar feedback objetivo"}, {"id": "next", "label": "Combinar proximos passos"}], "correctOrder": ["prepare", "ask", "share", "next"], "explanation": "Comece com contexto, crie espaco de escuta, depois entregue o feedback e feche com acordo concreto."}, "rules_schema": None, "tags": ["soft-skill", "career-type:tech", "communication"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Regras de ouro do alinhamento tecnico", "description": "Veja os principios curtos que evitam retrabalho em times de tecnologia.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Alinhamento Tecnico", "rules": [{"id": "r1", "title": "Contexto primeiro", "description": "Explique o problema antes de propor a solucao."}, {"id": "r2", "title": "Risco explicito", "description": "Declare bloqueios e riscos cedo."}, {"id": "r3", "title": "Dono claro", "description": "Toda decisao precisa de responsavel."}, {"id": "r4", "title": "Proximo passo", "description": "Saia de reunioes com acao definida."}]}, "tags": ["soft-skill", "career-type:tech", "communication"]},

    {"type": ContentItemType.ARTICLE, "title": "Storytelling de design para stakeholders", "description": "Como vender melhor contexto e decisao visual para produto e negocio.", "external_url": "https://www.nngroup.com/articles/storytelling/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:design", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Apresentando seu processo de design", "description": "Video sobre como expor raciocinio e iteracoes sem soar defensivo.", "external_url": None, "video_url": "https://www.youtube.com/embed/3KANI2dpXLw", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:design", "presentation"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: maturidade de colaboracao em design", "description": "Teste sua forma de colaborar com PMs, devs e usuarios.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce valida restricoes com engenharia cedo?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce apresenta racional das decisoes de design?", "options": ["Sempre", "Raramente"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:design", "teamwork"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Mapa de alinhamento UX", "description": "Documente os principais alinhamentos que faltam entre descoberta, produto e entrega.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:design", "alignment"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Briefing de apresentacao de case", "description": "Preencha um roteiro curto para apresentar seu case de design com clareza.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "problem", "label": "Problema", "type": "textarea", "placeholder": "Qual problema esse case resolveu?"}, {"name": "impact", "label": "Impacto", "type": "textarea", "placeholder": "Quais resultados essa solucao gerou?"}]}, "tags": ["soft-skill", "career-type:design", "storytelling"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Monte a estrutura de uma critica de design", "description": "Classifique cada frase no momento certo de uma critica saudavel.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "categorize", "prompt": "Arraste cada frase para a coluna correta.", "pieces": [{"id": "p1", "label": "Quais restricoes precisamos considerar?"}, {"id": "p2", "label": "Isso esta feio"}, {"id": "p3", "label": "Vamos conectar ao objetivo do usuario"}, {"id": "p4", "label": "Que trade-off foi assumido aqui?"}], "categories": ["Boa pratica", "Evitar"], "correctCategories": {"p1": "Boa pratica", "p2": "Evitar", "p3": "Boa pratica", "p4": "Boa pratica"}, "explanation": "Boas criticas focam em objetivo, restricoes e trade-offs; comentarios vagos devem ser evitados."}, "rules_schema": None, "tags": ["soft-skill", "career-type:design", "feedback"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Principios de comunicacao em design", "description": "Regras curtas para defender decisoes com clareza e abertura.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Design Communication", "rules": [{"id": "r1", "title": "Defenda com contexto", "description": "Relacione a decisao com o problema do usuario."}, {"id": "r2", "title": "Mostre iteracao", "description": "Explique o que mudou e por quê."}, {"id": "r3", "title": "Escute objecoes", "description": "Use perguntas para entender restricoes."}, {"id": "r4", "title": "Feche com trade-off", "description": "Mostre o que foi priorizado e o que ficou de fora."}]}, "tags": ["soft-skill", "career-type:design", "communication"]},

    {"type": ContentItemType.ARTICLE, "title": "Comunicacao persuasiva em marketing", "description": "Como alinhar criacao, performance e negocio sem ruído.", "external_url": "https://blog.hubspot.com/marketing", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:marketing", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Priorizacao de campanhas sem caos", "description": "Video sobre foco, negociacao e alinhamento de expectativas em marketing.", "external_url": None, "video_url": "https://www.youtube.com/embed/ZV7J9dI3L6w", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:marketing", "prioritization"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: maturidade de priorizacao em marketing", "description": "Teste sua forma de decidir entre volume, marca e performance.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce define objetivo unico por campanha?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce documenta trade-offs de canal?", "options": ["Sempre", "Nunca"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:marketing", "planning"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Checklist de handoff de campanha", "description": "Monte um checklist de passagem entre criacao, mídia e analytics.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:marketing", "alignment"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Plano de comunicacao de campanha", "description": "Estruture objetivo, stakeholders e cadencia de comunicacao de uma campanha relevante.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "objective", "label": "Objetivo da campanha", "type": "text", "placeholder": "Ex: gerar leads qualificados"}, {"name": "cadence", "label": "Cadencia de alinhamento", "type": "textarea", "placeholder": "Quem atualiza quem e com qual frequencia"}]}, "tags": ["soft-skill", "career-type:marketing", "communication"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Ordene uma retrospectiva de campanha", "description": "Monte a ordem correta de uma conversa de aprendizado de campanha.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "order", "prompt": "Arraste os blocos para a sequencia certa.", "pieces": [{"id": "goal", "label": "Relembrar objetivo"}, {"id": "data", "label": "Revisar dados-chave"}, {"id": "learn", "label": "Extrair aprendizados"}, {"id": "next", "label": "Definir proximas acoes"}], "correctOrder": ["goal", "data", "learn", "next"], "explanation": "A equipe aprende melhor quando revisita objetivo, interpreta os dados e fecha com acoes."}, "rules_schema": None, "tags": ["soft-skill", "career-type:marketing", "retrospective"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Regras de ouro da colaboracao em marketing", "description": "Quatro regras simples para evitar caos entre criacao, midia e analytics.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Marketing Flow", "rules": [{"id": "r1", "title": "Um objetivo", "description": "Cada campanha precisa de uma meta principal."}, {"id": "r2", "title": "Dono por entrega", "description": "Toda frente deve ter responsavel claro."}, {"id": "r3", "title": "Dados visiveis", "description": "Performance deve ser compartilhada cedo."}, {"id": "r4", "title": "Ritmo curto", "description": "Ajuste rapido vence planejamento perfeito."}]}, "tags": ["soft-skill", "career-type:marketing", "alignment"]},

    {"type": ContentItemType.ARTICLE, "title": "Escuta ativa em vendas", "description": "Aprenda a ouvir sinais reais do cliente antes de tentar persuadir.", "external_url": "https://www.salesforce.com/resources/articles/active-listening/", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:sales", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Como conduzir discovery sem interrogatorio", "description": "Video com tecnicas de discovery mais humanas e eficientes.", "external_url": None, "video_url": "https://www.youtube.com/embed/i5mYphUoOCs", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:sales", "discovery"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: maturidade comercial consultiva", "description": "Teste sua abordagem de discovery, empatia e follow-up.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce valida a dor do cliente antes do pitch?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Seu follow-up resume decisoes e proximos passos?", "options": ["Sempre", "Nao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:sales", "empathy"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Mapa de objeções recorrentes", "description": "Liste as objeções mais comuns e como voce responde sem soar defensivo.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:sales", "objections"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Roteiro de discovery consultivo", "description": "Preencha perguntas-chave para tornar seu discovery mais profundo.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "context", "label": "Contexto do cliente", "type": "textarea", "placeholder": "O que sabemos antes da reuniao"}, {"name": "questions", "label": "Perguntas abertas", "type": "textarea", "placeholder": "Quais perguntas vao revelar a dor real?"}]}, "tags": ["soft-skill", "career-type:sales", "discovery"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Classifique frases de discovery", "description": "Separe frases entre discovery consultivo e pitch precoce.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "categorize", "prompt": "Arraste cada frase para a coluna correta.", "pieces": [{"id": "p1", "label": "Como isso impacta a meta do time?"}, {"id": "p2", "label": "Nossa ferramenta resolve tudo"}, {"id": "p3", "label": "O que voce ja tentou antes?"}, {"id": "p4", "label": "Posso mostrar um demo agora"}], "categories": ["Discovery", "Pitch cedo demais"], "correctCategories": {"p1": "Discovery", "p2": "Pitch cedo demais", "p3": "Discovery", "p4": "Pitch cedo demais"}, "explanation": "Discovery eficaz aprofunda contexto antes de posicionar a solucao."}, "rules_schema": None, "tags": ["soft-skill", "career-type:sales", "discovery"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Regras de ouro da venda consultiva", "description": "Princípios simples para conduzir conversas comerciais mais maduras.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Consultative Sales", "rules": [{"id": "r1", "title": "Ouça primeiro", "description": "Entenda o problema antes de vender."}, {"id": "r2", "title": "Valide impacto", "description": "Quantifique ou qualifique a dor."}, {"id": "r3", "title": "Confirme proximo passo", "description": "Toda conversa precisa de continuidade clara."}, {"id": "r4", "title": "Evite overpromise", "description": "Credibilidade vale mais que pressa."}]}, "tags": ["soft-skill", "career-type:sales", "communication"]},

    {"type": ContentItemType.ARTICLE, "title": "Comunicacao executiva em financas", "description": "Como traduzir numeros em recomendacoes claras para decisores.", "external_url": "https://hbr.org/topic/finance-and-accounting", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:finance", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Storytelling com dados financeiros", "description": "Video sobre como apresentar analises financeiras com contexto e impacto.", "external_url": None, "video_url": "https://www.youtube.com/embed/0fKG95kh4Dk", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:finance", "storytelling"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: maturidade analitica em financas", "description": "Teste sua capacidade de comunicar risco, causa e recomendacao.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce sempre fecha com recomendacao?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce destaca variacao versus meta?", "options": ["Sempre", "Nunca"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:finance", "analysis"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Resumo executivo de fechamento", "description": "Crie um resumo de 5 linhas para um fechamento mensal ficticio.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:finance", "communication"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Template de recomendacao financeira", "description": "Preencha um modelo simples para ligar numero, causa e decisao recomendada.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "signal", "label": "Principal sinal", "type": "text", "placeholder": "Ex: margem abaixo da meta"}, {"name": "recommendation", "label": "Recomendacao", "type": "textarea", "placeholder": "Que acao voce recomenda e por quê?"}]}, "tags": ["soft-skill", "career-type:finance", "decision-making"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Ordene um update executivo", "description": "Monte a ordem ideal para apresentar um risco financeiro importante.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "order", "prompt": "Arraste para a melhor sequencia executiva.", "pieces": [{"id": "signal", "label": "Sinal principal"}, {"id": "cause", "label": "Causa"}, {"id": "impact", "label": "Impacto"}, {"id": "action", "label": "Acao recomendada"}], "correctOrder": ["signal", "cause", "impact", "action"], "explanation": "Comunicação executiva eficaz começa pelo sinal, contextualiza a causa, mostra impacto e fecha com acao."}, "rules_schema": None, "tags": ["soft-skill", "career-type:finance", "communication"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Regras de ouro da analise financeira", "description": "Leitura curta e visual para relatórios mais claros e úteis.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Finance Clarity", "rules": [{"id": "r1", "title": "Abra com o sinal", "description": "Destaque a variacao relevante logo de inicio."}, {"id": "r2", "title": "Explique a causa", "description": "Mostre por que o numero mudou."}, {"id": "r3", "title": "Conecte impacto", "description": "Traga implicacoes para o negocio."}, {"id": "r4", "title": "Recomende", "description": "Sempre feche com proxima acao."}]}, "tags": ["soft-skill", "career-type:finance", "analysis"]},

    {"type": ContentItemType.ARTICLE, "title": "Gestao de alinhamento em operacoes", "description": "Como evitar gargalos com rituais e comunicacao mais clara entre times.", "external_url": "https://asana.com/resources/team-communication", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:operations", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Priorizacao operacional sem apagar incendio", "description": "Video sobre como reagir menos e operar com cadencia.", "external_url": None, "video_url": "https://www.youtube.com/embed/m7f9Q4Jj0hQ", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:operations", "prioritization"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: maturidade operacional", "description": "Teste sua prontidao para delegar, priorizar e reduzir gargalos.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce revisa gargalos semanalmente?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce tem criterio de prioridade documentado?", "options": ["Sim", "Nao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:operations", "prioritization"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Mapa de gargalos do fluxo", "description": "Identifique os 3 principais gargalos do seu fluxo atual e proponha uma acao para cada um.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:operations", "process"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Plano de cadencia operacional", "description": "Defina uma rotina semanal simples para acompanhar fluxo, riscos e prioridades.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "rituals", "label": "Rituais semanais", "type": "textarea", "placeholder": "Quais rituais sustentam o fluxo?"}, {"name": "owners", "label": "Responsaveis", "type": "textarea", "placeholder": "Quem responde por cada etapa critica?"}]}, "tags": ["soft-skill", "career-type:operations", "planning"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Monte uma retro operacional", "description": "Organize os blocos de uma reuniao curta de melhoria operacional.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "order", "prompt": "Arraste os passos para a ordem ideal.", "pieces": [{"id": "goal", "label": "Relembrar objetivo do fluxo"}, {"id": "issue", "label": "Listar gargalos"}, {"id": "cause", "label": "Explorar causa-raiz"}, {"id": "next", "label": "Definir acoes e donos"}], "correctOrder": ["goal", "issue", "cause", "next"], "explanation": "Retro eficaz cria contexto, aponta gargalos, investiga causa e fecha com dono e prazo."}, "rules_schema": None, "tags": ["soft-skill", "career-type:operations", "retrospective"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Regras de ouro da operacao sem caos", "description": "Princípios para reduzir retrabalho e melhorar fluidez operacional.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Ops Flow", "rules": [{"id": "r1", "title": "Torne visivel", "description": "Problemas precisam aparecer cedo."}, {"id": "r2", "title": "Priorize em conjunto", "description": "Critério alinhado evita urgência artificial."}, {"id": "r3", "title": "Feche lacunas", "description": "Toda exceção precisa de tratamento claro."}, {"id": "r4", "title": "Aprenda rapido", "description": "Revise o fluxo toda semana."}]}, "tags": ["soft-skill", "career-type:operations", "process"]},

    {"type": ContentItemType.ARTICLE, "title": "Soft skills universais para qualquer carreira", "description": "Os fundamentos de comunicacao, foco e colaboracao aplicados a qualquer contexto profissional.", "external_url": "https://www.coursera.org/articles/soft-skills", "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:other", "communication"]},
    {"type": ContentItemType.VIDEO, "title": "Como ganhar clareza profissional", "description": "Video sobre como comunicar melhor seus objetivos e prioridades de carreira.", "external_url": None, "video_url": "https://www.youtube.com/embed/KxGRhd_iWuE", "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:other", "clarity"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz: fundamentos de soft skills", "description": "Teste sua base em foco, colaboracao, comunicacao e autogestao.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Voce costuma registrar prioridades da semana?", "options": ["Sim", "Nao"], "correctIndex": 0}, {"prompt": "Voce pede feedback de forma ativa?", "options": ["Sim", "Nao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:other", "self-management"]},
    {"type": ContentItemType.ACTION_TASK, "title": "Mapa pessoal de melhoria", "description": "Liste 3 soft skills que mais impactariam sua carreira nos proximos 90 dias.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "tags": ["soft-skill", "career-type:other", "reflection"]},
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Plano de desenvolvimento de soft skills", "description": "Monte um plano simples para praticar uma soft skill por semana.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "skill", "label": "Soft skill foco", "type": "text", "placeholder": "Ex: comunicacao"}, {"name": "practice", "label": "Como vai praticar", "type": "textarea", "placeholder": "Que situacoes reais usara para treinar?"}]}, "tags": ["soft-skill", "career-type:other", "planning"]},
    {"type": ContentItemType.SCENARIO_BUILDER, "title": "Ordene uma conversa de alinhamento", "description": "Monte a estrutura ideal de uma conversa curta de alinhamento profissional.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": {"mode": "order", "prompt": "Arraste para a sequencia ideal.", "pieces": [{"id": "context", "label": "Explicar contexto"}, {"id": "listen", "label": "Ouvir o outro lado"}, {"id": "proposal", "label": "Propor proximo passo"}, {"id": "confirm", "label": "Confirmar acordo"}], "correctOrder": ["context", "listen", "proposal", "confirm"], "explanation": "Boas conversas partem de contexto, escuta, proposta e fechamento claro."}, "rules_schema": None, "tags": ["soft-skill", "career-type:other", "communication"]},
    {"type": ContentItemType.RULES_RADIAL, "title": "Regras de ouro das soft skills", "description": "Os principios centrais para evoluir em qualquer carreira.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": {"centerTitle": "Core Soft Skills", "rules": [{"id": "r1", "title": "Escute com intencao", "description": "Escuta ativa melhora colaboração."}, {"id": "r2", "title": "Priorize com clareza", "description": "Foco reduz ansiedade e ruído."}, {"id": "r3", "title": "Peça feedback", "description": "Aprender mais rápido depende disso."}, {"id": "r4", "title": "Feche combinados", "description": "Ação clara constrói confiança."}]}, "tags": ["soft-skill", "career-type:other", "communication"]},
]

CHAIN_STAGE_SEED_ITEMS = [
    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: assertividade em tech", "description": "Descreva uma situacao recente em que voce poderia ter sido mais assertivo com seu time.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "context", "label": "Contexto", "type": "textarea", "placeholder": "Onde aconteceu e quem estava envolvido?"}, {"name": "newApproach", "label": "Nova abordagem", "type": "textarea", "placeholder": "O que voce falaria de forma mais assertiva hoje?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:tech"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: comunicacao assertiva tech", "description": "Valide se voce absorveu os principios de comunicacao assertiva no contexto de produto e engenharia.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Ao discordar de uma decisao tecnica, qual abordagem e mais assertiva?", "options": ["Questionar com contexto e proposta", "Criticar em publico sem dados", "Evitar falar para nao gerar conflito"], "correctIndex": 0}, {"prompt": "Qual frase melhora alinhamento em uma discussao de prazo?", "options": ["Nao vai dar e pronto", "Com escopo atual, risco X aumenta; proponho Y", "Faz ai do jeito que der"], "correctIndex": 1}, {"prompt": "Quando receber feedback dificil, voce deve:", "options": ["Responder defensivamente", "Ouvir, confirmar entendimento e propor ajuste", "Ignorar"], "correctIndex": 1}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:tech"]},
    {"type": ContentItemType.MATCHING_GAME, "title": "Matching: resposta assertiva em times tech", "description": "Associe cada situacao comum de time com a resposta assertiva mais eficaz.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": {"prompt": "Conecte cada situacao com a melhor resposta.", "pairs": [{"left": "PR atrasado sem atualizacao", "right": "Alinhar bloqueio e novo ETA com o time"}, {"left": "Conflito entre dev e produto", "right": "Recentrar conversa no objetivo e trade-offs"}, {"left": "Feedback sobre qualidade do codigo", "right": "Pedir exemplos objetivos e combinar melhoria"}, {"left": "Mudanca urgente de escopo", "right": "Explicar impacto e renegociar prioridade"}], "successMessage": "Boa. Você conectou contexto e resposta de forma madura.", "errorMessage": "Revise os pares com foco em clareza, respeito e proxima acao."}, "dialogue_schema": None, "tags": ["chain-stage", "career-type:tech"]},
    {"type": ContentItemType.DIALOGUE_SIMULATOR, "title": "Simulador: feedback dificil entre devs", "description": "Conduza uma conversa delicada de feedback e observe os efeitos de cada escolha.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": {"title": "Feedback para um colega que esta interrompendo o time", "startNodeId": "n1", "nodes": [{"id": "n1", "speaker": "Colega", "text": "Nao entendi porque voce marcou esta conversa.", "options": [{"id": "n1o1", "label": "Voce interrompe demais nas reunioes.", "nextNodeId": "n2_bad"}, {"id": "n1o2", "label": "Quero alinhar um ponto para trabalharmos melhor juntos.", "nextNodeId": "n2_good"}]}, {"id": "n2_bad", "speaker": "Colega", "text": "Nossa, isso foi agressivo. Nao concordo.", "options": [{"id": "n2bo1", "label": "Mas e verdade, todo mundo acha isso.", "outcome": {"title": "Conversa travada", "evaluation": "A abordagem acusatoria gerou defensividade e nao criou abertura para mudanca."}}, {"id": "n2bo2", "label": "Desculpa, vou reformular com exemplos.", "nextNodeId": "n2_good"}]}, {"id": "n2_good", "speaker": "Colega", "text": "Ok, pode falar.", "options": [{"id": "n2go1", "label": "Na review de ontem, voce interrompeu 3 vezes e o time saiu sem decisao.", "nextNodeId": "n3"}, {"id": "n2go2", "label": "E so um feeling meu, talvez nada.", "outcome": {"title": "Mensagem diluida", "evaluation": "Sem fato concreto, a conversa perde foco e dificilmente gera compromisso."}}]}, {"id": "n3", "speaker": "Colega", "text": "Entendi. O que voce sugere?", "options": [{"id": "n3o1", "label": "Nas proximas duas semanas, vamos testar turnos de fala e registrar decisoes.", "outcome": {"title": "Evolucao conjunta", "evaluation": "Excelente. Houve contexto, evidencias e acordo pratico de melhoria."}}, {"id": "n3o2", "label": "So para de fazer isso.", "outcome": {"title": "Acordo fraco", "evaluation": "Faltou um combinado observavel. A chance de recaida aumenta."}}]}]}, "tags": ["chain-stage", "career-type:tech"]},

    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: postura em criticas de design", "description": "Descreva uma reuniao em que voce precisou defender uma decisao visual sob pressao.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "moment", "label": "Momento", "type": "textarea", "placeholder": "Qual foi o contexto da critica?"}, {"name": "response", "label": "Resposta melhor", "type": "textarea", "placeholder": "Como responderia com mais clareza e empatia?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:design"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: comunicacao de design", "description": "Cheque sua capacidade de argumentar escolhas de design com contexto e trade-offs.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Qual argumento fortalece uma decisao visual?", "options": ["Gosto pessoal", "Objetivo do usuario e resultado esperado", "Comparacao sem contexto"], "correctIndex": 1}, {"prompt": "Ao receber critica dura, a melhor reacao inicial e:", "options": ["Interromper e se defender", "Escutar, perguntar e alinhar criterio", "Encerrar a discussao"], "correctIndex": 1}, {"prompt": "Trade-off em design significa:", "options": ["Escolher com base em evidencias e restricoes", "Buscar perfeicao absoluta", "Evitar decisao"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:design"]},

    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: alinhamento de campanhas", "description": "Relembre uma campanha recente em que faltou alinhamento entre criacao, midia e analytics.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "gap", "label": "Principal falha de alinhamento", "type": "textarea", "placeholder": "O que se perdeu no handoff?"}, {"name": "fix", "label": "Ajuste pratico", "type": "textarea", "placeholder": "Qual ritual simples evitaria repeticao?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:marketing"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: comunicacao em marketing", "description": "Valide seu dominio de foco, priorizacao e comunicacao entre frentes de marketing.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Uma campanha deve ter:", "options": ["Varios objetivos concorrentes", "Um objetivo principal claro", "Objetivo definido no fim"], "correctIndex": 1}, {"prompt": "Ao surgir conflito de canal, voce deve:", "options": ["Escalar sem dados", "Comparar impacto e decidir trade-off", "Executar tudo"], "correctIndex": 1}, {"prompt": "Ritmo de alinhamento eficiente e:", "options": ["Esporadico", "Curto e frequente", "Apenas no fechamento"], "correctIndex": 1}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:marketing"]},

    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: discovery em vendas", "description": "Descreva uma conversa comercial onde voce poderia ter investigado melhor a dor do cliente.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "lostSignal", "label": "Sinal perdido", "type": "textarea", "placeholder": "Que pista de necessidade voce ignorou?"}, {"name": "newQuestion", "label": "Pergunta melhor", "type": "textarea", "placeholder": "Que pergunta aberta usaria hoje?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:sales"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: venda consultiva", "description": "Teste se sua abordagem de discovery e follow-up esta realmente consultiva.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Antes de apresentar solucao, voce deve:", "options": ["Entender impacto e contexto", "Ir direto ao demo", "Falar de preco"], "correctIndex": 0}, {"prompt": "Follow-up forte inclui:", "options": ["Resumo de dor e proximo passo", "Mensagem generica", "Somente material comercial"], "correctIndex": 0}, {"prompt": "Pergunta consultiva eficaz e:", "options": ["Gostou da proposta?", "O que acontece se nada mudar nos proximos 3 meses?", "Quer fechar hoje?"], "correctIndex": 1}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:sales"]},

    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: comunicacao executiva em financas", "description": "Reflita sobre uma analise que nao gerou acao apesar de dados fortes.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "signal", "label": "Sinal principal", "type": "textarea", "placeholder": "Qual variacao importava mais?"}, {"name": "action", "label": "Acao sugerida", "type": "textarea", "placeholder": "Como recomendaria a decisao de forma objetiva?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:finance"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: storytelling financeiro", "description": "Valide se suas analises conectam numero, causa, impacto e recomendacao.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Uma boa apresentacao financeira comeca por:", "options": ["Detalhe tecnico", "Sinal relevante", "Planilha completa"], "correctIndex": 1}, {"prompt": "Depois do sinal, o ideal e:", "options": ["Pular para conclusao", "Explicar causa e impacto", "Trocar de assunto"], "correctIndex": 1}, {"prompt": "Fechamento forte sempre traz:", "options": ["Nova planilha", "Acao recomendada", "Mais dados sem decisao"], "correctIndex": 1}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:finance"]},

    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: cadencia em operacoes", "description": "Descreva um gargalo recorrente e como voce poderia ter alinhado donos e prazos melhor.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "bottleneck", "label": "Gargalo", "type": "textarea", "placeholder": "Onde o fluxo travou?"}, {"name": "ownership", "label": "Novo combinado", "type": "textarea", "placeholder": "Que dono, prazo e ritual evitariam repeticao?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:operations"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: fluidez operacional", "description": "Meça sua habilidade de priorizar e manter fluxo sem modo incendio.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Priorizacao madura exige:", "options": ["Urgencia de quem fala mais alto", "Criterio compartilhado", "Decisao isolada"], "correctIndex": 1}, {"prompt": "Para reduzir gargalos, o primeiro passo e:", "options": ["Mapear o fluxo atual", "Cobrar mais velocidade", "Adicionar reunioes longas"], "correctIndex": 0}, {"prompt": "Toda melhoria operacional deve fechar com:", "options": ["Boa intencao", "Dono, prazo e sinal de sucesso", "Novos termos"], "correctIndex": 1}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:operations"]},

    {"type": ContentItemType.INTERACTIVE_FORM, "title": "Reflexao: soft skill em contexto real", "description": "Registre uma conversa recente em que uma resposta mais clara teria melhorado o resultado.", "external_url": None, "video_url": None, "quiz_schema": None, "diagram_url": None, "form_schema": {"fields": [{"name": "situation", "label": "Situacao", "type": "textarea", "placeholder": "O que aconteceu?"}, {"name": "betterResponse", "label": "Resposta alternativa", "type": "textarea", "placeholder": "Como agiria de modo mais claro e colaborativo?"}]}, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:other"]},
    {"type": ContentItemType.QUIZ, "title": "Quiz aplicado: fundamentos de colaboracao", "description": "Valide seu entendimento de comunicacao clara, escuta ativa e combinados.", "external_url": None, "video_url": None, "quiz_schema": {"questions": [{"prompt": "Escuta ativa significa:", "options": ["Esperar sua vez de falar", "Confirmar entendimento antes de responder", "Concordar com tudo"], "correctIndex": 1}, {"prompt": "Prioridade clara depende de:", "options": ["Objetivo + criterio", "Urgencia percebida", "Opiniao pessoal"], "correctIndex": 0}, {"prompt": "Conversa produtiva termina com:", "options": ["Combinado observavel", "Promessa vaga", "Silencio"], "correctIndex": 0}]}, "diagram_url": None, "form_schema": None, "scenario_schema": None, "rules_schema": None, "matching_schema": None, "dialogue_schema": None, "tags": ["chain-stage", "career-type:other"]},
]

CHAIN_LINKS = {
    "Feedback para engenheiros": "Reflexao: assertividade em tech",
    "Reflexao: assertividade em tech": "Quiz aplicado: comunicacao assertiva tech",
    "Quiz aplicado: comunicacao assertiva tech": "Matching: resposta assertiva em times tech",
    "Matching: resposta assertiva em times tech": "Simulador: feedback dificil entre devs",
    "Apresentando seu processo de design": "Reflexao: postura em criticas de design",
    "Reflexao: postura em criticas de design": "Quiz aplicado: comunicacao de design",
    "Priorizacao de campanhas sem caos": "Reflexao: alinhamento de campanhas",
    "Reflexao: alinhamento de campanhas": "Quiz aplicado: comunicacao em marketing",
    "Como conduzir discovery sem interrogatorio": "Reflexao: discovery em vendas",
    "Reflexao: discovery em vendas": "Quiz aplicado: venda consultiva",
    "Storytelling com dados financeiros": "Reflexao: comunicacao executiva em financas",
    "Reflexao: comunicacao executiva em financas": "Quiz aplicado: storytelling financeiro",
    "Priorizacao operacional sem apagar incendio": "Reflexao: cadencia em operacoes",
    "Reflexao: cadencia em operacoes": "Quiz aplicado: fluidez operacional",
    "Como ganhar clareza profissional": "Reflexao: soft skill em contexto real",
    "Reflexao: soft skill em contexto real": "Quiz aplicado: fundamentos de colaboracao",
}

SEED_ITEMS = BASE_SEED_ITEMS + SOFT_SKILL_SEED_ITEMS + CHAIN_STAGE_SEED_ITEMS


def run() -> None:
    db = SessionLocal()
    try:
        existing_titles = set(db.scalars(select(ContentItem.title)))
        inserted = 0
        updated = 0
        for item in SEED_ITEMS:
            if item["title"] in existing_titles:
                existing = db.scalar(select(ContentItem).where(ContentItem.title == item["title"]))
                if existing is not None:
                    existing.type = item["type"]
                    existing.description = item["description"]
                    existing.external_url = item["external_url"]
                    existing.video_url = item["video_url"]
                    existing.quiz_schema = item["quiz_schema"]
                    existing.diagram_url = item["diagram_url"]
                    existing.form_schema = item["form_schema"]
                    existing.scenario_schema = item.get("scenario_schema")
                    existing.rules_schema = item.get("rules_schema")
                    existing.matching_schema = item.get("matching_schema")
                    existing.dialogue_schema = item.get("dialogue_schema")
                    existing.follow_up_content_item_id = None
                    existing.tags = item["tags"]
                    existing.is_active = True
                    updated += 1
                continue

            db.add(
                ContentItem(
                    type=item["type"],
                    title=item["title"],
                    description=item["description"],
                    external_url=item["external_url"],
                    video_url=item["video_url"],
                    quiz_schema=item["quiz_schema"],
                    diagram_url=item["diagram_url"],
                    form_schema=item["form_schema"],
                    scenario_schema=item.get("scenario_schema"),
                    rules_schema=item.get("rules_schema"),
                    matching_schema=item.get("matching_schema"),
                    dialogue_schema=item.get("dialogue_schema"),
                    follow_up_content_item_id=None,
                    tags=item["tags"],
                    is_active=True,
                )
            )
            inserted += 1

        db.flush()

        all_titles = [item["title"] for item in SEED_ITEMS]
        items_by_title = {
            item.title: item
            for item in db.scalars(select(ContentItem).where(ContentItem.title.in_(all_titles)))
        }

        for item in items_by_title.values():
            item.follow_up_content_item_id = None

        for source_title, target_title in CHAIN_LINKS.items():
            source = items_by_title.get(source_title)
            target = items_by_title.get(target_title)
            if source is not None and target is not None:
                source.follow_up_content_item_id = target.id

        db.commit()
        print(f"Seed concluido. Inseridos: {inserted}. Atualizados: {updated}.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
