"""initial_schema

Revision ID: cca771ed5ba7
Revises: 
Create Date: 2026-08-16 16:50:41.179007

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cca771ed5ba7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('COURSE', 'CERTIFICATION', 'ARTICLE', 'ACTION_TASK', name='content_item_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('free_step_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('onboarding_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_job', sa.String(length=255), nullable=False),
    sa.Column('dream_job', sa.String(length=255), nullable=True),
    sa.Column('goal', sa.Enum('GROW_CURRENT_JOB', 'SWITCH_JOB', 'FIND_JOB_ABROAD', 'MOVE_ABROAD', name='goal_type'), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=False),
    sa.Column('weekly_time_availability', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_responses_user_id'), 'onboarding_responses', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PREMIUM', name='subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', name='subscription_status'), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'MERCADO_PAGO', name='payment_provider'), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('career_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_response_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='career_path_status'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_response_id'], ['onboarding_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_onboarding_response_id'), 'career_paths', ['onboarding_response_id'], unique=True)
    op.create_index(op.f('ix_career_paths_user_id'), 'career_paths', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='payment_status'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('ai_generation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_path_id', sa.UUID(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_logs_career_path_id'), 'ai_generation_logs', ['career_path_id'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_user_id'), 'ai_generation_logs', ['user_id'], unique=False)
    op.create_table('path_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_path_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_reference_id', sa.UUID(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'UNLOCKED', 'COMPLETED', name='path_step_status'), nullable=False),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_reference_id'], ['content_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_path_id', 'order_index', name='uq_path_steps_career_path_order_index')
    )
    op.create_index(op.f('ix_path_steps_career_path_id'), 'path_steps', ['career_path_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('path_step_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['path_step_id'], ['path_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'path_step_id', name='uq_user_progress_user_step')
    )
    op.create_index(op.f('ix_user_progress_path_step_id'), 'user_progress', ['path_step_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_path_step_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_path_steps_career_path_id'), table_name='path_steps')
    op.drop_table('path_steps')
    op.drop_index(op.f('ix_ai_generation_logs_user_id'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_career_path_id'), table_name='ai_generation_logs')
    op.drop_table('ai_generation_logs')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_career_paths_user_id'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_onboarding_response_id'), table_name='career_paths')
    op.drop_table('career_paths')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_onboarding_responses_user_id'), table_name='onboarding_responses')
    op.drop_table('onboarding_responses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('content_items')
    # ### end Alembic commands ###