"""descreva_a_mudanca

Revision ID: 8587e973af76
Revises: f1a2b3c4d5e6
Create Date: 2026-08-19 18:07:52.708871

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8587e973af76'
down_revision: str | None = 'f1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_note_user_step'), table_name='notes', postgresql_where='(path_step_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_note_user_step'), 'notes', ['user_id', 'path_step_id'], unique=True, postgresql_where='(path_step_id IS NOT NULL)')
    # ### end Alembic commands ###